// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type ExampleProductMasterBasicData struct {
	Product             sql.NullString `json:"product"`
	ProductDesc         sql.NullString `json:"productDesc"`
	Baseunit            sql.NullString `json:"baseunit"`
	Validitystartdate   sql.NullTime   `json:"validitystartdate"`
	Productgroup        sql.NullString `json:"productgroup"`
	Division            sql.NullString `json:"division"`
	Grossweight         sql.NullString `json:"grossweight"`
	Weightunit          sql.NullString `json:"weightunit"`
	Sizeordimensiontext sql.NullString `json:"sizeordimensiontext"`
	Productstandardid   sql.NullString `json:"productstandardid"`
}
